---
- name: Install and configure Kafka
  hosts: kafka_nodes
  become: yes
  become_method: su
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Kafka
      get_url:
        url: https://downloads.apache.org/kafka/2.8.0/kafka_2.13-2.8.0.tgz
        dest: /tmp/kafka.tgz

    - name: Extract Kafka
      unarchive:
        src: /tmp/kafka.tgz
        dest: /opt/
        remote_src: yes

    - name: Create Kafka user
      user:
        name: kafka
        home: /home/kafka
        shell: /bin/bash
        state: present

    - name: Set up Kafka systemd service
      copy:
        dest: /etc/systemd/system/kafka.service
        content: |
          [Unit]
          Description=Apache Kafka
          After=network.target

          [Service]
          User=kafka
          ExecStart=/opt/kafka_2.13-2.8.0/bin/kafka-server-start.sh /opt/kafka_2.13-2.8.0/config/server.properties
          ExecStop=/opt/kafka_2.13-2.8.0/bin/kafka-server-stop.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify: restart kafka

  handlers:
    - name: restart kafka
      systemd:
        name: kafka
        state: restarted
